workflows:
  expo_android:
    name: Expo Android APK Build
    environment:
      vars:
        EAS_BUILD_PROFILE: release
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Android APK
        script: npx eas build -p android --profile release --non-interactive
    artifacts:
      - ./build/android/*.apk
    publishing:
      email:
        recipients:
          - vishalvrk97@gmail.com
